// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATQaDI7ZYXyleN1bs7u-ukm0TbgeUahuY',
    appId: '1:918409601108:android:5b393eb2a34efd59924dc1',
    messagingSenderId: '918409601108',
    projectId: 'qb-academia-news',
    storageBucket: 'qb-academia-news.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8xMYwubEM0EwBnErV39wXzywa6oB_2Q',
    appId: '1:918409601108:ios:03a17f290e665c27924dc1',
    messagingSenderId: '918409601108',
    projectId: 'qb-academia-news',
    storageBucket: 'qb-academia-news.firebasestorage.app',
    iosBundleId: 'com.example.qbAcademia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn8xMYwubEM0EwBnErV39wXzywa6oB_2Q',
    appId: '1:918409601108:ios:03a17f290e665c27924dc1',
    messagingSenderId: '918409601108',
    projectId: 'qb-academia-news',
    storageBucket: 'qb-academia-news.firebasestorage.app',
    iosBundleId: 'com.example.qbAcademia',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: '1:918409601108:web:REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: '918409601108',
    projectId: 'qb-academia-news',
    authDomain: 'qb-academia-news.firebaseapp.com',
    storageBucket: 'qb-academia-news.firebasestorage.app',
  );
}
